# -*- coding: utf-8 -*-
"""Background_removal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jbj1ZgfzGrl6ku6rvxghCsSp1gChXDJ7
"""

import nibabel as nib
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Load the NIfTI image
nifti_output_path_1 = "/content/drive/My Drive/Datasets/nifti/output.nii.gz"
nifti_img = nib.load(nifti_output_path_1)

# Get the data array from the NIfTI image
data = nifti_img.get_fdata()

# Choose a slice to display (e.g., the middle slice along the z-axis)
slice_index = data.shape[-1] // 2

# Plot the slice
plt.imshow(data[:, :, slice_index], cmap='gray')
plt.axis('off')
plt.title(' MRI Image')
plt.show()

def remove_background(data, nifti_img , threshold):

    # Apply thresholding to segment the background
    background_mask = data <= threshold

    # Create a masked array to remove the background
    masked_data = np.ma.masked_array(data, mask=background_mask)

    # Create a new NIfTI image with the background removed
    new_nii_img = nib.Nifti1Image(masked_data, nifti_img.affine)

    return new_nii_img

# Define threshold for background removal
def get_threshold_from_user():
    input_str = input("Enter the desired threshold : ")
    thr_str = tuple(map(int, input_str.split(',')))
    return thr_str

threshold = get_threshold_from_user()  # Adjust threshold value as needed
background_removed_nifti = remove_background(data, nifti_img, threshold)
#nib.save(background_removed_nifti, output_nifti_file)

# Plot the background removed image
background_removed_data = background_removed_nifti.get_fdata()
plt.imshow(background_removed_data[:, :, background_removed_data.shape[2] // 2], cmap='gray')
plt.title('Background Removed MRI Image')
plt.axis('')
plt.show()